version: '3.8'

services:
  nats:
    build:
      context: ./nats-server
      dockerfile: Dockerfile
    container_name: nats-server
    ports:
      - "4222:4222"    # NATS port
      - "42070:42070"  # WebSocket port
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "42069:42069"
    environment:
      - SPRING_APPLICATION_NAME=backend
      - SERVER_PORT=42069
      - NATS_URL=nats://nats:4222
    networks:
      - app-network
    depends_on:
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:42069/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend
      - nats

networks:
  app-network:
    driver: bridge
