version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:nats
    depends_on:
      - nats

  nats:
    build:
      context: ../nats-server
      dockerfile: Dockerfile
    container_name: nats-server-dev
    ports:
      - "4222:4222"    # NATS port
      - "42070:42070"  # WebSocket port
      - "8222:8222"    # Monitoring port
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
